### ISSUE TITLE
[v0.8.0] documentation updates

### ISSUE THREAD

**Issue by sundowndev** [cloudskiff/driftctl-docs#52]
Update documentation according to what changed in version 0.8.0 :

- [x] Sentry behavior https://github.com/cloudskiff/driftctl/pull/452 (#53)
- [x] Unsupported TF versions https://github.com/cloudskiff/driftctl/pull/361 (#54)
- [x] Driftignore generator https://github.com/cloudskiff/driftctl/pull/433 (#55) (**removed in #58**)
- [x] Terraform Cloud backend https://github.com/cloudskiff/driftctl/pull/458 (#47)
- [x] Glob support for enumerators https://github.com/cloudskiff/driftctl/pull/353 (#57)
